Update permissions-deployment-schema.json
microsoftgraph/kibali pull request #42
Opened 2023-05-29 09:39 UTC by athmangude

### Changed
- Set scheme to enum
- Set type of permission member to array
- Moved permission environment to definitions

2023-07-05 14:03 UTC, athmangude commented
@darrelmiller and @wandeg, please review this PR merging into [microsoftgraph:migratespecs](https://github.com/microsoftgraph/kibali/tree/migratespecs)

2023-07-08 21:40 UTC, darrelmiller commented on specs/permissions-deployment-schema.json
> +          "scheme": {
```suggestion
          "scheme": {
            "type": "string",
```

2023-07-08 21:42 UTC, darrelmiller commented on specs/permissions-deployment-schema.json
> +            "type": "string"
```suggestion
            "type": "string",
            "enum": ["public","PPE","fairfax","mooncake","USSec","USNat"]
```

2023-07-08 21:43 UTC, darrelmiller commented on specs/permissions-deployment-schema.json
> +            "enum": ["Application", "DelegatedPersonal", "DelegatedWork"]
```suggestion
            "enum": ["application", "delegatedPersonal", "delegatedWork"]
```

2023-07-08 21:45 UTC, darrelmiller requested changes
I made some suggestions to address James' comments.

2023-07-08 21:46 UTC, closed without merging